services:
  postgres:
    image: postgres:15
    container_name: ecommerce_dwh_postgres
    environment:
      POSTGRES_DB: ecommerce_dwh
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5434:5432"
    volumes:
      - ecommerce_dwh_pgdata:/var/lib/postgresql/data

volumes:
  ecommerce_dwh_pgdata: